//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.ServiceModel.Web.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.ServiceModel.Http.Client.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The async result has already been ended..
        /// </summary>
        internal static string AsyncResultAlreadyEnded {
            get {
                return ResourceManager.GetString("AsyncResultAlreadyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The async result &apos;{0}&apos; completed twice..
        /// </summary>
        internal static string AsyncResultCompletedTwice {
            get {
                return ResourceManager.GetString("AsyncResultCompletedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query expression cannot be executed because it does not start with a method call..
        /// </summary>
        internal static string ExpressionMustStartWithMethodCall {
            get {
                return ResourceManager.GetString("ExpressionMustStartWithMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The async result &apos;{0}&apos; is not implemented correctly..
        /// </summary>
        internal static string InvalidAsyncResultImplementation {
            get {
                return ResourceManager.GetString("InvalidAsyncResultImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string MethodNotSupported {
            get {
                return ResourceManager.GetString("MethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri &apos;{0}&apos; is not a relative Uri..
        /// </summary>
        internal static string QueryResourceUriMustBeRelative {
            get {
                return ResourceManager.GetString("QueryResourceUriMustBeRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request message of a web query can only be HTTP GET..
        /// </summary>
        internal static string WebQueryRequestMessageCanOnlyBeHttpGet {
            get {
                return ResourceManager.GetString("WebQueryRequestMessageCanOnlyBeHttpGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status code of the HTTP response of the web query is &apos;{0}&apos;, &apos;{1}&apos;, which indicates an error has occurred in handling the HTTP request..
        /// </summary>
        internal static string WebQueryResponseDidNotReturnStatusOK {
            get {
                return ResourceManager.GetString("WebQueryResponseDidNotReturnStatusOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of the HTTP message is not in XML or JSON format, which is required in order to deserialize the message into objects..
        /// </summary>
        internal static string WebQueryResponseMessageInUnsupportedFormat {
            get {
                return ResourceManager.GetString("WebQueryResponseMessageInUnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media type of the response cannot be null where there is a ContentType header.
        /// </summary>
        internal static string WebQueryResponseMessageMissingMediaType {
            get {
                return ResourceManager.GetString("WebQueryResponseMessageMissingMediaType", resourceCulture);
            }
        }
    }
}
